server:
  port: 8080
  servlet:
    context-path: /api/v1/metadata

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: Metadata
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

#logging:
#  level:
#    root: DEBUG
