version: '3'
services:
  metadata:
    image: kamaraj/api-gateway-metadata:1.0.0
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JAVA_OPTS=-DAPP_ENV=local
    healthcheck:
      test: curl --fail http://localhost:8081/actuator/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
