AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates API Gateway
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV)
    AllowedValues: [ 'DEV' ]
  Platform:
    Type: String
    Default: 'GW'
    Description: Platform Name
  LambdaStackName:
    Type: String
    Description: Name of the stack used to create Lambda functions
  LoadBalancerStackName:
    Type: String
    Description: Name of the stack used to create Load balancer
  RoleStackName:
    Type: String
    Description: Name of the stack used to create required IAM roles
Resources:
  ApiGatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${Environment}-${Platform}-API-GW-01'
      Description: API Gateway with Lambda authorizer
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::ImportValue: !Join [':', [!Ref 'RoleStackName', 'ApiGatewayCloudWatchRoleArn']]

  # Validator for request parameters and headers
  RequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: 'Validate request parameters'
      RestApiId: !Ref ApiGatewayApi
      ValidateRequestBody: false
      ValidateRequestParameters: true

  TokenResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ParentId: !GetAtt ApiGatewayApi.RootResourceId
      PathPart: token
  ApiGatewayTokenMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      RestApiId: !Ref ApiGatewayApi
      ResourceId: !Ref TokenResource
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestValidatorId: !Ref RequestValidator
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations'
          - LambdaArn:
              Fn::ImportValue: !Join [':', [!Ref 'LambdaStackName', 'TokenGenFunctionArn']]

  TokenGenFunctionApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Fn::ImportValue: !Join [':', [!Ref 'LambdaStackName', 'TokenGenFunctionArn']]
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApi}/*/*/*"

  RestApiAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${Platform}-REST-API-AUTHORIZER-ROLE-05'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'lambda:invokeFunction'
                Effect: 'Allow'
                Resource:
                  Fn::ImportValue: !Join [':', [!Ref 'LambdaStackName', 'TokenValidatorFunctionArn']]
  RestApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: !Sub '${Environment}-${Platform}-API-GW-AUTHORIZER-01'
      AuthorizerCredentials: !GetAtt RestApiAuthorizerRole.Arn
      AuthorizerUri: !Sub
        - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations'
        - LambdaArn:
            Fn::ImportValue: !Join [':', [!Ref 'LambdaStackName', 'TokenValidatorFunctionArn']]
      AuthorizerResultTtlInSeconds: 300
      Type: REQUEST
      IdentitySource: 'method.request.header.token'
      RestApiId: !Ref ApiGatewayApi
  TokenValidatorFunctionApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Fn::ImportValue: !Join [':', [!Ref 'LambdaStackName', 'TokenValidatorFunctionArn']]
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApi}/*/*/*"

  VpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: !Sub '${Environment}-${Platform}-API-GW-VPC-LINK-01'
      Description: API GW VPC Link to NLB
      TargetArns:
        - Fn::ImportValue: !Join [':', [!Ref 'LoadBalancerStackName', 'NetworkLoadBalancerARN']]

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ParentId: !GetAtt ApiGatewayApi.RootResourceId
      PathPart: 'api'
  V1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ParentId: !Ref ApiResource
      PathPart: 'v1'
  MetadataResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ParentId: !Ref V1Resource
      PathPart: 'metadata'

  StocksResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ParentId: !Ref MetadataResource
      PathPart: 'stocks'

  StocksPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      RestApiId: !Ref ApiGatewayApi
      ResourceId: !Ref StocksResource
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref RestApiAuthorizer
      ApiKeyRequired: true
      RequestValidatorId: !Ref RequestValidator
      RequestParameters:
        method.request.header.token: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: POST
        ConnectionType: VPC_LINK
        ConnectionId: !Sub '${VpcLink}'
        Uri: !Sub
          - 'http://${NlbDns}/api/v1/metadata/stocks'
          - NlbDns:
              Fn::ImportValue: !Join [ ':', [ !Ref 'LoadBalancerStackName', 'LoadBalancerDNS' ] ]
        TimeoutInMillis: 29000
        RequestParameters:
          integration.request.header.App-User-Name: 'context.authorizer.principalId'
          integration.request.header.App-Account-Name: 'context.authorizer.accountName'
          integration.request.header.Request-Id: 'context.authorizer.requestId'

  StocksGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      RestApiId: !Ref ApiGatewayApi
      ResourceId: !Ref StocksResource
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref RestApiAuthorizer
      ApiKeyRequired: true
      RequestValidatorId: !Ref RequestValidator
      RequestParameters:
        method.request.header.token: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        ConnectionType: VPC_LINK
        ConnectionId: !Sub '${VpcLink}'
        Uri: !Sub
          - 'http://${NlbDns}/api/v1/metadata/stocks'
          - NlbDns:
              Fn::ImportValue: !Join [ ':', [ !Ref 'LoadBalancerStackName', 'LoadBalancerDNS' ] ]
        TimeoutInMillis: 29000
        RequestParameters:
          integration.request.header.App-User-Name: 'context.authorizer.principalId'
          integration.request.header.App-Account-Name: 'context.authorizer.accountName'
          integration.request.header.Request-Id: 'context.authorizer.requestId'

  StocksIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayApi
      ParentId: !Ref StocksResource
      PathPart: '{stockId}'

  StocksByIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      RestApiId: !Ref ApiGatewayApi
      ResourceId: !Ref StocksIdResource
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref RestApiAuthorizer
      ApiKeyRequired: true
      RequestValidatorId: !Ref RequestValidator
      RequestParameters:
        method.request.header.token: true
        method.request.path.stockId: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        ConnectionType: VPC_LINK
        ConnectionId: !Sub '${VpcLink}'
        Uri: !Sub
          - 'http://${NlbDns}/api/v1/metadata/stocks/{stockId}'
          - NlbDns:
              Fn::ImportValue: !Join [ ':', [ !Ref 'LoadBalancerStackName', 'LoadBalancerDNS' ] ]
        TimeoutInMillis: 29000
        CacheKeyParameters:
          - 'method.request.path.stockId'
        RequestParameters:
          integration.request.path.stockId: 'method.request.path.stockId'
          integration.request.header.App-User-Name: 'context.authorizer.principalId'
          integration.request.header.App-Account-Name: 'context.authorizer.accountName'
          integration.request.header.Request-Id: 'context.authorizer.requestId'

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayTokenMethod
      - StocksPostMethod
      - StocksGetMethod
      - StocksByIdGetMethod
    Properties:
      RestApiId: !Ref ApiGatewayApi
      Description: API Gateway Deployment

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref Environment
      Description: API Gateway DEV stage
      RestApiId: !Ref ApiGatewayApi
      DeploymentId: !Ref ApiGatewayDeployment
      # Default rate limit for the stage
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingBurstLimit: 1
          ThrottlingRateLimit: 1

  # Same throttle settings for all methods
  UsagePlanOne:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: PLAN1_100_REQUESTS_PER_DAY_WITH_BURST_10_RATE_20
      Description: >- 
        100 requests per day quota with default burst limit as 10 requests and rate limit as 
        20 requests per second
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref ApiGatewayStage
      Quota:
        Limit: 100
        Period: DAY
      Throttle:
        # Concurrent requests
        BurstLimit: 10
        # Rate at which requests can arrive per second
        RateLimit: 20

  # Override default throttle settings at method level
  UsagePlanTwo:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: PLAN2_500_REQUESTS_PER_DAY_WITH_BURST_15_RATE_20_METHOD_LEVEL_THROTTLE
      Description: >-
        500 requests per day quota with default burst limit as 15 requests and rate limit as 
        20 requests per second. Default throttle settings are overridden at method level.
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref ApiGatewayStage
          Throttle:
            "/token/POST":
              BurstLimit: 5
              RateLimit: 10
            "/api/v1/metadata/stocks/POST":
              BurstLimit: 5
              RateLimit: 10
            "/api/v1/metadata/stocks/GET":
              BurstLimit: 10
              RateLimit: 20
            "/api/v1/metadata/stocks/{stockId}/GET":
              BurstLimit: 10
              RateLimit: 20
      Quota:
        Limit: 500
        Period: DAY
      Throttle:
        # Concurrent requests
        BurstLimit: 15
        # Rate at which requests can arrive per second
        RateLimit: 20

  # CustomerOne
  ApiKeyCustomerOne:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: CUSTOMER_1
      Description: API Key for customer 1
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: !Ref ApiGatewayStage
  CustomerOneUsagePlan:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKeyCustomerOne
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanOne

  # CustomerTwo
  ApiKeyCustomerTwo:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: CUSTOMER_2
      Description: API Key for customer 2
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: !Ref ApiGatewayStage
  CustomerTwoUsagePlan:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKeyCustomerTwo
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlanTwo
